_target_: graphextractor.arcan.ArcanGraphExtractor
cleaner:
  _target_: graphcleaner.cleaner.ArcanGraphCleaner
  edges_type_remove: ["isChildOf", "isImplementationOf", "nestedTo",
                      "belongsTo", "implementedBy", "definedBy",
                      "containerIsAfferentOf", "unitIsAfferentOf"]
arcan_path: ${base_path}/src/arcan
repository_path: ${repository_path}
arcan_out: ${out_path}
logs_path: ${out_path}/logs
force_run: False
